server:
  port: 8761

spring:
  application:
    name: eurekaserver

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/