spring:
  application:
    name: apigateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: microservicioviajes
            uri: lb://microservicioviajes
            predicates:
              - Path=/api/viajes/**
          - id: microserviciocuentas-usuario
            uri: lb://microserviciocuentas
            predicates:
              - Path=/api/usuarios/**
          - id: microserviciocuentas-cuentas
            uri: lb://microserviciocuentas
            predicates:
              - Path=/api/mercadopago/cuentas**
          - id: microserviciocuentas-roles
            uri: lb://microserviciocuentas
            predicates:
              - Path=/api/roles/**
          - id: microservicioestaciones
            uri: lb://microservicioestaciones
            predicates:
              - Path=/api/estaciones/**
          - id: microserviciomonopatines
            uri: lb://microserviciomonopatines
            predicates:
              - Path=/api/monopatines/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}