spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: microservicioviajes
          uri: lb://microservicioviajes
          predicates:
            - Path=/api/viajes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}