server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: microservicioviajes
          uri: http://localhost:8086
          predicates:
            - Path=/api/viajes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG